# -*- coding: utf-8 -*-
"""Notebook1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_hH7zG2DRIlV7s14qeyxQCBnBHF87RIP
"""

list1 = [45,20,30,5]
print(min(list1))
print(max(list1))
print(sum(list1))

list1 = ["45","20","30","5"]
list1.sort()
print(list1)
print(min(list1))
print(max(list1))
# print(sum(list1))

sq  = []
for i in range(10):
  sq.append(i*i)
print(sq)

sq = [i*i for i in range(10)]
print(sq)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

new_fruits = []
for fruit in fruits:
  if "a" in fruit:
    new_fruits.append(fruit)

print(new_fruits)

new_fruits = [fruit for fruit in fruits if "a" in fruit]
print(new_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

new_fruits = []
for fruit in fruits:
  if "a" in fruit:
    new_fruits.append(fruit)
  else:
    new_fruits.append("orange")

print(new_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
new_fruits = [fruit if "a" in fruit else "orange" for fruit in fruits]
print(new_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
copy_fruits = fruits
fruits.append("orange")
print(fruits)
print(copy_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
copy_fruits = fruits.copy()
fruits.append("orange")
print(fruits)
print(copy_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
copy_fruits = fruits[:]
fruits.append("orange")
print(fruits)
print(copy_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
copy_fruits = list(fruits)
fruits.append("orange")
print(fruits)
print(copy_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
copy_fruits = []+fruits
fruits.append("orange")
print(fruits)
print(copy_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
copy_fruits = []
copy_fruits.extend(fruits)
fruits.append("orange")
print(fruits)
print(copy_fruits)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
copy_fruits = [fruit for fruit in fruits]
fruits.append("orange")
print(fruits)
print(copy_fruits)

thislist = [4,3,1,2]
thislist.sort()
print(thislist)

thislist = [4,3,1,2]
thislist.sort(reverse= True)
print(thislist)

fruits = ["apple","mango", "cherry", "kiwi", "banana"]
fruits.sort()
print(fruits)

fruits = ["apple","mango", "cherry", "Kiwi", "banana"]
fruits.sort()
print(fruits)

fruits = ["apple","mango", "cherry", "Kiwi", "banana"]
fruits.sort(key = str.lower)
print(fruits)

def func(string1):
  return string1.lower()

fruits = ["apple","mango", "cherry", "Kiwi", "banana"]
fruits.sort(key = func)
print(fruits)

fruits = ["apple",1, "cherry", "Kiwi", "banana"]
fruits.sort()
print(fruits)

def func(n):
  return str(n).lower()

fruits = ["apple",1, "cherry", "Kiwi", "banana"]
fruits.sort(key = func)
print(fruits)

fruits = ["apple","mango", "cherry", "Kiwi", "banana"]
copy_fruits = fruits.copy()
fruits.reverse()
print(fruits)
print(copy_fruits)

print(help(list.sort))

str1 ="Rice"
str1.upper()

tuples = (200,10)
print(tuples)
print(len(tuples))
print(type(tuples))

tuples = tuple((200,10))
print(tuples)

tuple1 = ("apple", "banana", "cherry")
tuple2 = (1, 5, 7, 9, 3)
tuple3 = (True, False, False)

tuple1 = ("abc", 34, True, 40, "male")

"""Tuple
1. Ordered
2. Unchangable(update,add,remove)
3. duplicate allowed
"""

tuples = (200,10)
tuples[0] = 250

tuple1 = ("apple", "banana", "cherry")
print(tuple1[:2])
print(tuple1[:-1])

tuples = (200,10,1,43,5,5,6)
print(tuples)
tuples = (250,10,1,43,5,5,6)
print(tuples)

tuples = (200,10,1,43,5,5,6)
list1 = list(tuples)
list1[0] = 250
tuples = tuple(list1)
print(tuples)

tuples = ()
print(type(tuples))

tuples = (10,)
print(type(tuples))

tuples = (200,10,1,43,5,5,6)
tuples = (250,)+tuples[1:]
print(tuples)

tuples = (200,10,1,43,5,5,6)
tuples.append(100)

tuples = (200,10,1,43,5,5,6)
list1 = list(tuples)
list1.append(100)
tuples = tuple(list1)
print(tuples)

tuples = (200,10,1,43,5,5,6)
tuples = tuples+(100,)
print(tuples)