# -*- coding: utf-8 -*-
"""Notebook 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15UYq-yPxCaJHUCT1YZw_NrnyX3HxeHtC
"""

print("hello")

"""#String"""

message  ="hello"
message = 'hello'

"""# String index"""

message = "hello world"

print(message[0])
print(message[-1])

"""#String slicing"""

messgae = "hello world"

print(message[2:4])
print(message[:3])
print(message[6:])
print(message[-5:])

"""#string related function"""

message ="hello world"

print(len(message))

messgae = "Hello World"

print(message.lower())
print(message.upper())

"""#String count"""

message = "hello world"

print(message.count("l"))

"""# String find"""

message  = "hello world"

print(message.find("World"))

"""#String Replace"""

message = "hello world"

print(message.replace("world","universe"))
print(message.replace("l","x"))

"""#String  concat"""

a  ="hello"
b = "world"
c = a + " "+b
print(c)
c = f"{a} {b}"
print(c)

"""#Help"""

print(help(str.find))