# -*- coding: utf-8 -*-
"""Notebook11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AdG8vBzwxj-j-7KUYIvBbcriVQVgzKPz
"""

if(conditions)
{
    task1
    task2
}

if conditions:
  task1
  task2

a =10
b =20
print(a == b)
print(a != b)
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

a = int(input())
b = int(input())

if a>b:
  print("a is greater than b")

a = int(input())
b = int(input())

if a>b:
  print("a is greater than b")
elif a == b:
  print("a is equal to b")

a = int(input())
b = int(input())

if a>b:
  print("a is greater than b")
elif a == b:
  print("a is equal to b")
else:
  print("a is less than b")



"""#Short Hand If

"""

a = int(input())
b = int(input())

if a>b:print("a is greater than b")

"""#Short Hand If ... Else"""

a = int(input())
b = int(input())

if a>b:
  print(a)
else:
  print(b)

a = int(input())
b = int(input())

print(a) if a>b else print(b)

a = int(input())
b = int(input())

if a>b:
  print("a is greater than b")
elif a == b:
  print("a is equal to b")
else:
  print("a is less than b")

a = int(input())
b = int(input())

print("a is greater than b") if a>b else print("a is equal to b") if a == b else print("a is less than b")

if(condition1 || condition2)
{
    task1
}

if(condition1 && condition2)
{
    task1
}

if condition1 or condition2:
  task1
if condition1 and condition2:
  task1

a = int(input())

if a>=10 and a<=20:
  print("a is in between 10 to 20")
else:
  print("Wrong input")

"""# Nested IF"""

a = int(input())

if a>=10:
  if a<=20:
    print("a is in between 10 to 20")
  else:
    print("Wrong input")
else:
  print("Wrong input")

"""# Take 3 integer numbers from user and then print the maximum number [ Note: Must use nested if]

"""

a = int(input())
b = int(input())
c = int(input())

if a>b:
  if a>c:
    print(a)
  else:
    print(c)
else:
  if b>c:
    print(b)
  else:
    print(c)

"""# Take 4 integer numbers from user and then print the maximum number [ Note: Must use nested if]"""



"""#Pass"""

a = int(input())
b = int(input())

if a>b:
  pass
print("onno kaje")

"""#While"""

while(condition)
{
    task1
    task2
}

while condition:
  task1
  task2

i = 1
while i<=5:
  print(i)
  i+=1

i = 1
while i<=5:
  print(i)
  i+=1
else:
  print("done")

i = 1
while i<=5:
  print(i)
  i+=1
print("done")

"""# For"""

for i in range(1,6):
  print(i)

for i in range(1,6,2):
  print(i)

for i in range(6,1, -1):
  print(i)

for i in range(1,6):
  print(i)
else:
  print("what!!")

"""#continue"""

i = 1
while i<=5:
  if i==2:
    i+=1
    continue
  print(i)
  i+=1

"""#break"""

i = 1
while i<=5:
  if i==3:
    break
  print(i)
  i+=1

"""#Nested loop"""

4
*
**
***
****

n = int(input())
for i in range(1,n+1):
  for j  in range(1,i+1):
    print("*", end= "")
  print()

4
****
***
**
*