# -*- coding: utf-8 -*-
"""Notebook1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ie2DxBUIZU-KSveLXnv1ZNerLx3qdrvQ

#List Create
"""

mylist = ["apple","banana","cherry"]
print(mylist)

mylist = list(('apple', 'banana', 'cherry'))
print(mylist)

"""## List Comprehension

"""

n = int(input())
mylist = [0 for i in range(1,n+1)]
print(mylist)

for i in range(1,6):
  print(i*i)

print(type(mylist))

mylist = ["apple",1,"cherry"]
print(mylist)

i = 1
print(type(i))

"""1. Ordered
2. Changable (Add, Remove, Update)
3. Duplicate allowed
"""

mylist = ["apple","banana","cherry"]
print(mylist[2])

print(mylist[-2])

mylist = ["apple","banana","cherry"]
mylist[0] = "mango"
print(mylist)

mylist = ["apple","banana","cherry","apple"]

print(mylist)

mylist = ["apple","banana","cherry","apple"]
print(len(mylist))

list1 = [1,2,3,4]
list2 = [True, False, True]
list3 = ["apple","banana","cherry","apple"]

"""#List Slicing"""

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]

print(thislist[2:5])
print(thislist[:4])
print(thislist[4:])
print(thislist[-5:-2])
print(thislist[-5:5])

fruits = ["apple","banana","cherry"]

for fruit in fruits:
  print(fruit)

"""#Changable

## Update
"""

mylist = ["apple","banana","cherry"]
mylist[0] = "mango"
print(mylist)

mylist = ["apple","banana","cherry"]
mylist[0:2] = ["mango","orange"]
print(mylist)

mylist = ["apple","banana","cherry"]
mylist[0:2] = ["mango","orange","watermelon"]
print(mylist)

mylist = ["apple","banana","cherry"]
mylist[0:2] = ["mango"]
print(mylist)

mylist = ["apple","banana","cherry"]
mylist.insert(1,"mango")
print(mylist)

"""##Add

"""

mylist = ["apple","banana","cherry"]
mylist.append("mango")
print(mylist)

mylist = ["apple","banana","cherry"]
mylist.insert(0,"mango")
print(mylist)

mylist = ["apple","banana","cherry"]
mylist1  = ["mango","orange"]
mylist =mylist+mylist1
print(mylist)

mylist = ["apple","banana","cherry"]
mylist1  = ["mango","orange"]
mylist.extend(mylist1)
print(mylist)

"""#Remove"""

mylist = ["apple","banana","cherry"]

mylist.remove("apple")
print(mylist)

mylist = ["apple","banana","cherry","apple"]

mylist.remove("apple")
print(mylist)

mylist = ["apple","banana","cherry","apple"]

mylist.pop(2)
print(mylist)

mylist = ["apple","banana","cherry","apple"]

mylist.pop()
print(mylist)

mylist = ["apple","banana","cherry"]

del mylist[0:2]
print(mylist)

mylist = ["apple","banana","cherry"]

mylist[0:2]= []
print(mylist)

mylist = ["apple","banana","cherry"]

del mylist

mylist = []
print(type(mylist))
print(len(mylist))
print(mylist)

mylist = ["apple","banana","cherry"]
mylist.clear()
print(mylist)

"""#Looping Through a List"""

fruits = ["apple","banana","cherry"]

for fruit in fruits:
  print(fruit)

mylist = list(range(10))
print(mylist)

for i in range(10):
  print(i)

fruits = ["apple","banana","cherry"]

for i in range(len(fruits)):
  print(fruits[i])

print(help(list))