# -*- coding: utf-8 -*-
"""Lab_Test(01).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P1j8cXKpnhJOhme6yONNUejPmkL99dgG
"""



"""

1.   Take a positive integer number n from user. (marks: 1)
2. Define an empty list using list constructor.(marks: 1)
3. Write a program to append total n integer numbers (can be positive or negative) in the list by taking user input.[Hints: use for loop]. (marks: 3)
4. Write a program to sort the list on the basis of the square value of each number in the list. [Hints: use custom function]. (marks: 5)
5. Write a program to create a new list from the existing list by taking positve number directly and replacing the negative number with the absolute value. (marks: 5) [Must use list comprehension]

"""

# Ans: 1
n=int(input("Enter a positive number: "))


#Ans: 2
list=list()


#Ans: 3
for i in range(n):
    list.append(int(input()))

print(list)


#Ans: 4
def fun(num):
    return num*num

sorted_List=list.copy()

sorted_List.sort(key=fun)
print("Sorted in square values: ")
print(sorted_List)


#Ans: 5
new_list=[i if i>0 else abs(i) for i in list]
print("New List: ")
print(new_list)